# frozen_string_literal: true

module CabinetCraft
  module Manufacturing
    # Post-processor framework. A "program" is a neutral list of events built by
    # Cnc::Program; a post turns events into machine text. Nothing here is tied to one machine.
    #
    # Events (all coordinates are machine-frame millimetres, already origin/Z-adjusted; the post handles units):
    #   { 't' => 'comment', 'text' }            { 't' => 'tool', 'number', 'kind', 'diameter', 'rpm', 'desc' }
    #   { 't' => 'rapid',  'x','y','z' }        { 't' => 'linear', 'x','y','z','f' }
    #   { 't' => 'drill',  'x','y','z','r','safe','f' }   (z = hole bottom, r = retract plane)
    #   { 't' => 'drill_end' }                  { 't' => 'end', 'safe' }
    module CncPosts
      BANNER = 'Generated by CabinetCraft Pro. NOT verified on any machine: dry-run / simulate before cutting.'
      TEMPLATE_KEYS = %w[header tool_change rapid linear drill footer comment].freeze
      PLACEHOLDERS = %w[x y z f s t d r safe n text name units].freeze

      # Maps mm -> machine units and formats numbers.
      class Fmt
        def initialize(units, decimals)
          @factor = units == 'in' ? 1 / 25.4 : 1.0
          @dec = decimals
        end

        def num(mm)
          v = (mm * @factor).round(@dec)
          v = 0.0 if v.zero? # avoid "-0"
          s = format("%.#{@dec}f", v)
          s.include?('.') ? s.sub(/0+\z/, '').sub(/\.\z/, '') : s
        end

        def feed(mm_per_min)
          (mm_per_min * @factor).round(@dec > 2 ? 2 : @dec).then { |v| v == v.round ? v.round.to_s : v.to_s }
        end
      end

      class Post
        attr_reader :machine

        def initialize(machine)
          @machine = machine
          @fmt = Fmt.new(machine['units'], machine['decimals'])
          @n = 0
        end

        def line(text)
          return text unless machine['line_numbers'] && !text.start_with?('(', '%', ';')

          @n += 10
          "N#{@n} #{text}"
        end

        def f(mm)
          @fmt.num(mm)
        end

        def render(events, info)
          out = begin_program(info)
          @pos = {}
          events.each { |e| out.concat(Array(event(e))) }
          (out + end_program(info)).join("\n") + "\n"
        end

        # axes modal output: only changed axes are written
        def axes(x, y, z)
          parts = []
          { 'X' => x, 'Y' => y, 'Z' => z }.each do |ax, v|
            next if v.nil? || @pos[ax] == v

            @pos[ax] = v
            parts << "#{ax}#{f(v)}"
          end
          parts.join(' ')
        end

        def comment(text)
          "(#{text.to_s.gsub(/[()\r\n]/, ' ')})"
        end
      end

      class IsoPost < Post
        def begin_program(info)
          units = machine['units'] == 'in' ? 'G20' : 'G21'
          ["%", comment(BANNER), comment("#{info['name']} - #{info['sheet']}"), line("G90 #{units} G17 G40 G49")]
        end

        def end_program(_info)
          [line('M5'), line('M30'), '%']
        end

        def event(e)
          case e['t']
          when 'comment' then comment(e['text'])
          when 'tool' then [comment(e['desc']), line("T#{e['number']} M6"), line("S#{e['rpm']} M3")]
          when 'rapid' then (a = axes(e['x'], e['y'], e['z'])).empty? ? [] : line("G0 #{a}")
          when 'linear' then (a = axes(e['x'], e['y'], e['z'])).empty? ? [] : line("G1 #{a} F#{@fmt.feed(e['f'])}")
          when 'drill' then drill(e)
          when 'drill_end' then machine['canned_cycles'] ? line('G80') : []
          when 'end' then [line("G0 Z#{f(e['safe'])}"), line('G0 X0 Y0')]
          end
        end

        def drill(e)
          if machine['canned_cycles']
            @pos = {} # canned cycles move the axes themselves
            return line("G98 G81 X#{f(e['x'])} Y#{f(e['y'])} Z#{f(e['z'])} R#{f(e['r'])} F#{@fmt.feed(e['f'])}")
          end
          @pos = {}
          [line("G0 Z#{f(e['safe'])}"), line("G0 X#{f(e['x'])} Y#{f(e['y'])}"), line("G0 Z#{f(e['r'])}"),
           line("G1 Z#{f(e['z'])} F#{@fmt.feed(e['f'])}"), line("G0 Z#{f(e['safe'])}")]
        end
      end

      # GRBL-style: no tool changer (operator pause), no canned cycles.
      class GrblPost < Post
        def begin_program(info)
          units = machine['units'] == 'in' ? 'G20' : 'G21'
          [comment(BANNER), comment("#{info['name']} - #{info['sheet']}"), line("#{units} G90 G17")]
        end

        def end_program(_info)
          [line('M5'), line('G0 X0 Y0'), line('M2')]
        end

        def event(e)
          case e['t']
          when 'comment' then comment(e['text'])
          when 'tool' then [line('M5'), line("M0 #{comment("Change to T#{e['number']}: #{e['desc']}")}"), line("M3 S#{e['rpm']}")]
          when 'rapid' then (a = axes(e['x'], e['y'], e['z'])).empty? ? [] : line("G0 #{a}")
          when 'linear' then (a = axes(e['x'], e['y'], e['z'])).empty? ? [] : line("G1 #{a} F#{@fmt.feed(e['f'])}")
          when 'drill'
            @pos = {}
            [line("G0 Z#{f(e['safe'])}"), line("G0 X#{f(e['x'])} Y#{f(e['y'])}"), line("G0 Z#{f(e['r'])}"),
             line("G1 Z#{f(e['z'])} F#{@fmt.feed(e['f'])}"), line("G0 Z#{f(e['safe'])}")]
          when 'end' then [line("G0 Z#{f(e['safe'])}")]
          end
        end
      end

      # User-defined format driven by text templates with {placeholders}.
      class TemplatePost < Post
        def initialize(machine, templates)
          super(machine)
          @t = templates
        end

        def fill(key, vals)
          tpl = @t[key].to_s
          tpl.gsub(/\{(\w+)\}/) { vals.key?(Regexp.last_match(1)) ? vals[Regexp.last_match(1)].to_s : Regexp.last_match(0) }
        end

        def render(events, info)
          base = { 'name' => info['name'], 'units' => machine['units'] == 'in' ? 'G20' : 'G21', 'text' => BANNER }
          out = [fill('comment', base.merge('text' => BANNER)), fill('header', base)]
          events.each do |e|
            case e['t']
            when 'comment' then out << fill('comment', base.merge('text' => e['text']))
            when 'tool' then out << fill('tool_change', base.merge('t' => e['number'], 's' => e['rpm'], 'd' => @fmt.num(e['diameter']), 'text' => e['desc']))
            when 'rapid' then out << fill('rapid', xyz(e))
            when 'linear' then out << fill('linear', xyz(e).merge('f' => @fmt.feed(e['f'])))
            when 'drill' then out << fill('drill', xyz(e).merge('r' => f(e['r']), 'safe' => f(e['safe']), 'f' => @fmt.feed(e['f'])))
            when 'end' then out << fill('footer', base.merge('safe' => f(e['safe'])))
            end
          end
          out.reject!(&:empty?)
          out.each_with_index.map { |l, i| @t['numbered'] ? "N#{(i + 1) * 10} #{l}" : l }.join("\n") + "\n"
        end

        def xyz(e)
          { 'x' => f(e['x'] || 0), 'y' => f(e['y'] || 0), 'z' => f(e['z'] || 0) }
        end
      end

      BUILT_IN = [
        { 'id' => 'iso', 'name' => 'Generic ISO G-code (Fanuc-style, G81 drilling)', 'extension' => 'nc' },
        { 'id' => 'grbl', 'name' => 'GRBL-style (manual tool change, no canned cycles)', 'extension' => 'nc' }
      ].freeze

      DEFAULT_TEMPLATES = {
        'comment' => '({text})', 'header' => "%\nG90 {units} G17 G40 G49", 'tool_change' => "(Tool {t}: {text})\nT{t} M6\nS{s} M3",
        'rapid' => 'G0 X{x} Y{y} Z{z}', 'linear' => 'G1 X{x} Y{y} Z{z} F{f}',
        'drill' => "G0 Z{safe}\nG0 X{x} Y{y}\nG0 Z{r}\nG1 Z{z} F{f}\nG0 Z{safe}", 'footer' => "M5\nG0 Z{safe}\nG0 X0 Y0\nM30\n%"
      }.freeze

      module_function

      def validate_templates(t)
        raise ArgumentError, 'Templates must be a set of named text blocks' unless t.is_a?(Hash)

        out = {}
        TEMPLATE_KEYS.each do |k|
          v = t[k].to_s
          raise ArgumentError, "Template '#{k}' is empty" if v.strip.empty? && k != 'comment'
          raise ArgumentError, "Template '#{k}' is too long" if v.size > 2000

          v.scan(/\{(\w*)\}/).flatten.each do |ph|
            raise ArgumentError, "Unknown placeholder {#{ph}} in '#{k}' (allowed: #{PLACEHOLDERS.join(', ')})" unless PLACEHOLDERS.include?(ph)
          end
          out[k] = v
        end
        out['numbered'] = t['numbered'] ? true : false
        out
      end

      # custom: [{ 'id', 'name', 'templates', 'extension' }]
      def exist?(id, custom = [])
        BUILT_IN.any? { |p| p['id'] == id } || custom.any? { |p| p['id'] == id }
      end

      def list(custom = [])
        BUILT_IN + custom.map { |p| { 'id' => p['id'], 'name' => p['name'], 'extension' => p['extension'], 'custom' => true } }
      end

      def build(id, machine, custom = [])
        case id
        when 'iso' then IsoPost.new(machine)
        when 'grbl' then GrblPost.new(machine)
        else
          c = custom.find { |p| p['id'] == id } or raise KeyError, "Unknown post-processor '#{id}'"
          TemplatePost.new(machine, c['templates'])
        end
      end

      def extension(id, custom = [])
        (list(custom).find { |p| p['id'] == id } || {})['extension'] || 'nc'
      end
    end
  end
end
